import { NextRequest, NextResponse } from 'next/server';
import { createAirtableRecord } from '@/lib/airtable';
import { query } from '@/lib/db';
import { uploadToR2 } from '@/lib/r2';

const PROPOSAL_TABLE = process.env.AIRTABLE_PROPOSAL_TABLE || '';

export async function POST(req: NextRequest) {
  try {
    const data = await req.json();
    const {
      full_name, email, phone, address,
      property_type, roof_type, bill_range,
      system_selected, payment_type, price, lang,
    } = data;

    const missing: string[] = [];
    if (!full_name) missing.push('full_name');
    if (!email) missing.push('email');
    if (missing.length) {
      return NextResponse.json({ error: 'Missing required fields', missing }, { status: 400 });
    }

    const notes = [
      `Property: ${property_type || 'N/A'}`,
      `Roof: ${roof_type || 'N/A'}`,
      `Bill: ${bill_range || 'N/A'}`,
      `System: ${system_selected || 'N/A'}`,
      `Payment: ${payment_type || 'N/A'}`,
      `Price: ${price || 'N/A'}`,
      `Address: ${address || 'N/A'}`,
      phone ? `Phone: ${phone}` : '',
      `Lang: ${lang || 'es'}`,
    ].filter(Boolean).join('\n');

    const label = `[${system_selected || 'proposal'}] ${full_name} - ${new Date().toISOString().split('T')[0]}`;
    const dateStr = new Date().toISOString().split('T')[0];

    let dbOk = false;
    let airtableOk = false;
    let r2Url = '';
    const errors: { db?: string; airtable?: string; r2?: string } = {};
    let proposalId: number | null = null;

    // 1. Insert into RDS
    try {
      const res = await query(
        `INSERT INTO proposal_requests (
          full_name, email, phone, address,
          property_type, roof_type, bill_range,
          system_selected, payment_type, price,
          lang, form_source, follow_up_status, notes
        ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)
        RETURNING id`,
        [
          full_name, email, phone || null, address || null,
          property_type || null, roof_type || null, bill_range || null,
          system_selected || null, payment_type || null, price || null,
          lang || 'es', 'proposal-page', 'New', notes,
        ]
      );
      dbOk = !!res?.rowCount;
      proposalId = res?.rows?.[0]?.id || null;
    } catch (e) {
      errors.db = e instanceof Error ? e.message : String(e);
      console.error('[DB Proposal]', { email, err: errors.db });
    }

    // 2. Upload proposal document to Cloudflare R2
    try {
      const sanitizedEmail = email.replace(/[^a-zA-Z0-9]/g, '_');
      const ts = Date.now();

      const proposalDoc = {
        id: proposalId,
        full_name, email, phone, address,
        property_type, roof_type, bill_range,
        system_selected, payment_type, price,
        lang, notes, label,
        submitted_at: new Date().toISOString(),
      };

      const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Proposal - ${full_name}</title>
<style>body{font-family:Arial,sans-serif;max-width:700px;margin:40px auto;color:#1a1a1a}
h1{color:#F59E0B;border-bottom:2px solid #F59E0B;padding-bottom:8px}
h2{color:#333;margin-top:24px}
.row{display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid #eee}
.label{color:#666;font-weight:600}.value{font-weight:700}
.footer{margin-top:40px;color:#999;font-size:12px}</style></head>
<body>
<h1>Ancestro Solar Proposal</h1>
<h2>Customer</h2>
<div class="row"><span class="label">Name</span><span class="value">${full_name}</span></div>
<div class="row"><span class="label">Email</span><span class="value">${email}</span></div>
${phone ? `<div class="row"><span class="label">Phone</span><span class="value">${phone}</span></div>` : ''}
${address ? `<div class="row"><span class="label">Address</span><span class="value">${address}</span></div>` : ''}
<h2>Property</h2>
<div class="row"><span class="label">Type</span><span class="value">${property_type || 'N/A'}</span></div>
<div class="row"><span class="label">Roof</span><span class="value">${roof_type || 'N/A'}</span></div>
<div class="row"><span class="label">Monthly Bill</span><span class="value">${bill_range || 'N/A'}</span></div>
<h2>Selected System</h2>
<div class="row"><span class="label">System</span><span class="value">${system_selected || 'N/A'}</span></div>
<div class="row"><span class="label">Payment</span><span class="value">${payment_type || 'N/A'}</span></div>
<div class="row"><span class="label">Price</span><span class="value">${price || 'N/A'}</span></div>
<div class="footer">Generated by Ancestro AI · ${new Date().toLocaleDateString()}</div>
</body></html>`;

      const jsonKey = `proposals/${sanitizedEmail}/proposal_${ts}.json`;
      const htmlKey = `proposals/${sanitizedEmail}/proposal_${ts}.html`;

      await uploadToR2(Buffer.from(JSON.stringify(proposalDoc, null, 2)), jsonKey, 'application/json');
      await uploadToR2(Buffer.from(html), htmlKey, 'text/html');

      r2Url = `https://assets.ancestro.ai/${htmlKey}`;

      if (proposalId) {
        await query('UPDATE proposal_requests SET r2_url = $1 WHERE id = $2', [r2Url, proposalId]);
      }
    } catch (e) {
      errors.r2 = e instanceof Error ? e.message : String(e);
      console.error('[R2 Proposal]', { email, err: errors.r2 });
    }

    // 3. Airtable (optional)
    if (PROPOSAL_TABLE) {
      try {
        const fields: Record<string, unknown> = {};
        if (full_name) fields['Full Name'] = full_name;
        if (email) fields['Email'] = email;
        if (phone) fields['Phone'] = phone;
        if (address) fields['Address'] = address;
        if (property_type) fields['Property Type'] = property_type;
        if (roof_type) fields['Roof Type'] = roof_type;
        if (bill_range) fields['Bill Range'] = bill_range;
        if (system_selected) fields['System'] = system_selected;
        if (payment_type) fields['Payment Type'] = payment_type;
        if (price) fields['Price'] = price;
        if (lang) fields['Language'] = lang;
        if (r2Url) fields['R2 URL'] = r2Url;
        fields['Proposal Request'] = label;
        fields['Form Source'] = 'Proposal Page';
        fields['Follow-Up Status'] = 'New';
        fields['Submission Date'] = dateStr;
        fields['Notes'] = notes;

        await createAirtableRecord(PROPOSAL_TABLE, fields);
        airtableOk = true;
      } catch (e) {
        errors.airtable = e instanceof Error ? e.message : String(e);
        console.error('[Airtable Proposal]', { email, err: errors.airtable });
      }
    }

    if (!dbOk && !airtableOk) {
      return NextResponse.json(
        { success: false, error: 'All storage backends failed', db: false, airtable: false, errors },
        { status: 502 }
      );
    }

    return NextResponse.json({
      success: true,
      db: dbOk,
      airtable: airtableOk || !PROPOSAL_TABLE,
      r2: r2Url || null,
      ...((errors.db || errors.airtable || errors.r2) && { errors }),
    });
  } catch (err) {
    console.error('[Proposal API] Uncaught', err);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
